### ISSUE TITLE
Help display list Diagram 

### ISSUE THREAD

**Issue by Fa10175** [ric2016/openstreetmap_hooked#10]
on your tree i  can see the list diagram possible. 
but on my tree the bottom on the list are under the map
i use webtrees 1.7.16 in local with your last module version
theme webtrees 
thanks to tell me why i have not as you as display and how i can correct this

see yours 
![image](https://user-images.githubusercontent.com/10681601/76685046-f68a7380-6610-11ea-88b9-1d6e539134f6.png)

see for me
![image](https://user-images.githubusercontent.com/10681601/76685066-233e8b00-6611-11ea-8637-8d9f0f17e501.png)

**Comment by ric2016** [comment]
[That's weird! My server is at 1.7.15, but that shouldn't make any difference. Does this occur in different browsers?] 
Edit: Never mind, I can reproduce this locally.

In general, I'd recommend switching to webtrees 2.x sooner or later. For one thing, it has OSM support built-in, so you won't need additional modules (unless in combination with other functionality).

**Comment by ric2016** [comment]
The z-indexes in leaflet.css were too high, compared to the z-index of the dropdown menus.
Fixed in 1.7.16.1 (download latest zip).
